import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import ClientLayout from "@/components/layout-client";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const robotoMono = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${robotoMono.variable} `}>
        <ClientLayout>{children}</ClientLayout>
      </body>
    </html>
  );
}
